---
- name: Publishing our Website
  hosts: 192.168.50.11
  tasks:
  - name: Create websites directory under /home/vagrant/
    file:
      path: /home/vagrant/websites
      state: directory
      owner: vagrant
      group: vagrant
      mode: '0755'
  - name: Download website templates
    get_url:
      url: https://github.com/bazhang87/atd/blob/master/Demos/Linux/hacked_website_demo/sites.tgz?raw=true
      dest: /home/vagrant/websites
  - name: Extract sites.tgz into /home/vagrant/websites
    unarchive:
      src: /home/vagrant/websites/sites.tgz
      dest: /home/vagrant/websites
      remote_src: yes
  - name: Copy website to /var/www/html
    copy:
      src: /home/vagrant/websites/sites/website/
      dest: /var/www/html
      remote_src: true 
  - name: This will restore /var/www's context as determined by SELinux's system policy to /var/www and all folders and files below it.
    command: restorecon -R /var/www

